name: JavaEE Samples
title: Navigate your way trough EE via Tests
org: JavaEE Samples
issue_tracker: 'https://github.com/javaee-samples/javaee7-samples/issues'
base_url: ''
profiles:
  development:
    deploy: nil # force development as the default
  production:
    base_url: ''
    fingerprint_assets: true
    minify: true
    google_analytics: UA-18727998-5
    deploy:
      host: github_pages
      branch: master
      repository: upstream
